# Generated by Django 5.2 on 2025-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiondetail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='competitionprize',
            name='image',
        ),
        migrations.RemoveField(
            model_name='competitionsponsor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='competitionwinningteam',
            name='image',
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='tag',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('sponsor', 'Sponsor'), ('winner', 'Winner'), ('article', 'Article'), ('prize', 'Prize'), ('general', 'General'), ('detail', 'Detail')], max_length=10),
        ),
    ]
