# Generated by Django 5.2 on 2025-04-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_remove_competitiondetail_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='TeamRegistration',
        ),
    ]
