# Generated by Django 5.2 on 2025-04-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_delete_contactmessage_delete_teammember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionprize',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='competitionsponsor',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AlterUniqueTogether(
            name='competitionwinningteam',
            unique_together={('competition', 'position')},
        ),
        migrations.AddField(
            model_name='competition',
            name='content_image',
            field=models.ImageField(default=1, upload_to='competitions/detail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='detail_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='detail_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='scoreboard',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitionwinningteam',
            name='image',
            field=models.ImageField(default=1, upload_to='competition/winners/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to='competition.article'),
        ),
        migrations.AlterField(
            model_name='competitionwinningteam',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='competition.competition'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='tag',
            field=models.CharField(choices=[('article', 'Article'), ('gallery', 'Gallery'), ('sponsor', 'Sponsor'), ('main_prize', 'Main_Prize'), ('other_prize', 'Other_Prize'), ('general', 'General')], max_length=15),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.DeleteModel(
            name='CompetitionDetail',
        ),
        migrations.DeleteModel(
            name='CompetitionPrize',
        ),
        migrations.DeleteModel(
            name='CompetitionSponsor',
        ),
        migrations.RemoveField(
            model_name='competitionwinningteam',
            name='scoreboard',
        ),
    ]
