# Generated by Django 5.2 on 2025-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_remove_competitionprize_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='scoreboard',
            field=models.FileField(upload_to='competition/scoreboard/'),
        ),
    ]
