# Generated by Django 5.2 on 2025-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_alter_competition_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_logo',
            field=models.ImageField(default=1, upload_to='competitions/logo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='scoreboard',
            field=models.FileField(upload_to='competitions/scoreboard/'),
        ),
        migrations.AlterField(
            model_name='competitionwinningteam',
            name='image',
            field=models.ImageField(upload_to='competitions/winners/'),
        ),
    ]
