# Generated by Django 5.2 on 2025-04-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_competition_competition_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mediavideo',
            name='title',
        ),
    ]
