# Generated by Django 5.2 on 2025-04-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_remove_mediaimage_title_remove_mediavideo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
