# Generated by Django 5.2 on 2025-04-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_competition_created_at_competition_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='theme_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
