# Generated by Django 5.2 on 2025-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_competition_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimage',
            name='tag',
            field=models.CharField(choices=[('article', 'Article'), ('gallery', 'Gallery'), ('sponsor', 'Sponsor'), ('main_prize_laptop', 'Main_Prize_Laptop'), ('main_prize_phone', 'Main_Prize_Phone'), ('other_prize', 'Other_Prize'), ('general', 'General')], max_length=20),
        ),
    ]
